(cl:defpackage ssl_msgs-msg
  (:use )
  (:export
   "<ACTUATORCOMMAND>"
   "ACTUATORCOMMAND"
   "<BALLSTATE>"
   "BALLSTATE"
   "<GAMESTATE>"
   "GAMESTATE"
   "<GLOBALROBOTSTATE>"
   "GLOBALROBOTSTATE"
   "<GLOBALSTATE>"
   "GLOBALSTATE"
   "<LOCALROBOTSTATE>"
   "LOCALROBOTSTATE"
   "<LOCALSTATE>"
   "LOCALSTATE"
   "<MOTORCOMMAND>"
   "MOTORCOMMAND"
   "<ROBOTCOMMAND>"
   "ROBOTCOMMAND"
   "<TEAMCOMMAND>"
   "TEAMCOMMAND"
   "<TEAMPOSECOMMAND>"
   "TEAMPOSECOMMAND"
   "<VISUALIZATION>"
   "VISUALIZATION"
  ))

