"""autogenerated by genmsg_py from LocalState.msg. Do not edit."""
import roslib.message
import struct

import ssl_msgs.msg

class LocalState(roslib.message.Message):
  _md5sum = "e095c880d9c27373afe05b462a5a392d"
  _type = "ssl_msgs/LocalState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ssl_msgs/LocalRobotState[] robots #includes robots' local states

================================================================================
MSG: ssl_msgs/LocalRobotState
bool ball_possesion 	#true if it possess, false otherwise
uint8 battery		#battery level of the robot changes between [0-100]
float32 temp1 		#dummy
float32 temp2 		#dummy
float32 temp3 		#dummy

"""
  __slots__ = ['robots']
  _slot_types = ['ssl_msgs/LocalRobotState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       robots
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(LocalState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.robots is None:
        self.robots = []
    else:
      self.robots = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      length = len(self.robots)
      buff.write(_struct_I.pack(length))
      for val1 in self.robots:
        _x = val1
        buff.write(_struct_2B3f.pack(_x.ball_possesion, _x.battery, _x.temp1, _x.temp2, _x.temp3))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robots = []
      for i in xrange(0, length):
        val1 = ssl_msgs.msg.LocalRobotState()
        _x = val1
        start = end
        end += 14
        (_x.ball_possesion, _x.battery, _x.temp1, _x.temp2, _x.temp3,) = _struct_2B3f.unpack(str[start:end])
        val1.ball_possesion = bool(val1.ball_possesion)
        self.robots.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      length = len(self.robots)
      buff.write(_struct_I.pack(length))
      for val1 in self.robots:
        _x = val1
        buff.write(_struct_2B3f.pack(_x.ball_possesion, _x.battery, _x.temp1, _x.temp2, _x.temp3))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robots = []
      for i in xrange(0, length):
        val1 = ssl_msgs.msg.LocalRobotState()
        _x = val1
        start = end
        end += 14
        (_x.ball_possesion, _x.battery, _x.temp1, _x.temp2, _x.temp3,) = _struct_2B3f.unpack(str[start:end])
        val1.ball_possesion = bool(val1.ball_possesion)
        self.robots.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2B3f = struct.Struct("<2B3f")
