"""autogenerated by genmsg_py from Visualization.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class Visualization(roslib.message.Message):
  _md5sum = "1fffa6ca883aaeeeccdc951a2d04f5f6"
  _type = "ssl_msgs/Visualization"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point32 robot_position
geometry_msgs/Point32 force_vector

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
"""
  __slots__ = ['robot_position','force_vector']
  _slot_types = ['geometry_msgs/Point32','geometry_msgs/Point32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       robot_position,force_vector
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Visualization, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.robot_position is None:
        self.robot_position = geometry_msgs.msg.Point32()
      if self.force_vector is None:
        self.force_vector = geometry_msgs.msg.Point32()
    else:
      self.robot_position = geometry_msgs.msg.Point32()
      self.force_vector = geometry_msgs.msg.Point32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.robot_position.x, _x.robot_position.y, _x.robot_position.z, _x.force_vector.x, _x.force_vector.y, _x.force_vector.z))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.robot_position is None:
        self.robot_position = geometry_msgs.msg.Point32()
      if self.force_vector is None:
        self.force_vector = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.robot_position.x, _x.robot_position.y, _x.robot_position.z, _x.force_vector.x, _x.force_vector.y, _x.force_vector.z,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.robot_position.x, _x.robot_position.y, _x.robot_position.z, _x.force_vector.x, _x.force_vector.y, _x.force_vector.z))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.robot_position is None:
        self.robot_position = geometry_msgs.msg.Point32()
      if self.force_vector is None:
        self.force_vector = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.robot_position.x, _x.robot_position.y, _x.robot_position.z, _x.force_vector.x, _x.force_vector.y, _x.force_vector.z,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6f = struct.Struct("<6f")
