/* Auto-generated by genmsg_cpp for file /home/kadir/interconnection/workspace/robocup/system_design/robocup_ssl/ssl_msgs/msg/TeamPoseCommand.msg */
#ifndef SSL_MSGS_MESSAGE_TEAMPOSECOMMAND_H
#define SSL_MSGS_MESSAGE_TEAMPOSECOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "geometry_msgs/Pose2D.h"

namespace ssl_msgs
{
template <class ContainerAllocator>
struct TeamPoseCommand_ : public ros::Message
{
  typedef TeamPoseCommand_<ContainerAllocator> Type;

  TeamPoseCommand_()
  : target_poses()
  {
  }

  TeamPoseCommand_(const ContainerAllocator& _alloc)
  : target_poses(_alloc)
  {
  }

  typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _target_poses_type;
  std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  target_poses;


  ROS_DEPRECATED uint32_t get_target_poses_size() const { return (uint32_t)target_poses.size(); }
  ROS_DEPRECATED void set_target_poses_size(uint32_t size) { target_poses.resize((size_t)size); }
  ROS_DEPRECATED void get_target_poses_vec(std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other > & vec) const { vec = this->target_poses; }
  ROS_DEPRECATED void set_target_poses_vec(const std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other > & vec) { this->target_poses = vec; }
private:
  static const char* __s_getDataType_() { return "ssl_msgs/TeamPoseCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "18a79bb622b74b8f2b6ba9bacc51773d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "geometry_msgs/Pose2D[] target_poses 	#robots' target pose x,y,theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, target_poses);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, target_poses);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(target_poses);
    return size;
  }

  typedef boost::shared_ptr< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct TeamPoseCommand
typedef  ::ssl_msgs::TeamPoseCommand_<std::allocator<void> > TeamPoseCommand;

typedef boost::shared_ptr< ::ssl_msgs::TeamPoseCommand> TeamPoseCommandPtr;
typedef boost::shared_ptr< ::ssl_msgs::TeamPoseCommand const> TeamPoseCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ssl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "18a79bb622b74b8f2b6ba9bacc51773d";
  }

  static const char* value(const  ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x18a79bb622b74b8fULL;
  static const uint64_t static_value2 = 0x2b6ba9bacc51773dULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ssl_msgs/TeamPoseCommand";
  }

  static const char* value(const  ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Pose2D[] target_poses 	#robots' target pose x,y,theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const  ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.target_poses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TeamPoseCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ssl_msgs::TeamPoseCommand_<ContainerAllocator> & v) 
  {
    s << indent << "target_poses[]" << std::endl;
    for (size_t i = 0; i < v.target_poses.size(); ++i)
    {
      s << indent << "  target_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.target_poses[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SSL_MSGS_MESSAGE_TEAMPOSECOMMAND_H

