/* Auto-generated by genmsg_cpp for file /home/kadir/interconnection/workspace/robocup/system_design/robocup_ssl/ssl_msgs/msg/LocalRobotState.msg */
#ifndef SSL_MSGS_MESSAGE_LOCALROBOTSTATE_H
#define SSL_MSGS_MESSAGE_LOCALROBOTSTATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace ssl_msgs
{
template <class ContainerAllocator>
struct LocalRobotState_ : public ros::Message
{
  typedef LocalRobotState_<ContainerAllocator> Type;

  LocalRobotState_()
  : ball_possesion(false)
  , battery(0)
  , temp1(0.0)
  , temp2(0.0)
  , temp3(0.0)
  {
  }

  LocalRobotState_(const ContainerAllocator& _alloc)
  : ball_possesion(false)
  , battery(0)
  , temp1(0.0)
  , temp2(0.0)
  , temp3(0.0)
  {
  }

  typedef uint8_t _ball_possesion_type;
  uint8_t ball_possesion;

  typedef uint8_t _battery_type;
  uint8_t battery;

  typedef float _temp1_type;
  float temp1;

  typedef float _temp2_type;
  float temp2;

  typedef float _temp3_type;
  float temp3;


private:
  static const char* __s_getDataType_() { return "ssl_msgs/LocalRobotState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "91ec796323133e006b0a572e6a364407"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool ball_possesion 	#true if it possess, false otherwise\n\
uint8 battery		#battery level of the robot changes between [0-100]\n\
float32 temp1 		#dummy\n\
float32 temp2 		#dummy\n\
float32 temp3 		#dummy\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ball_possesion);
    ros::serialization::serialize(stream, battery);
    ros::serialization::serialize(stream, temp1);
    ros::serialization::serialize(stream, temp2);
    ros::serialization::serialize(stream, temp3);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ball_possesion);
    ros::serialization::deserialize(stream, battery);
    ros::serialization::deserialize(stream, temp1);
    ros::serialization::deserialize(stream, temp2);
    ros::serialization::deserialize(stream, temp3);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ball_possesion);
    size += ros::serialization::serializationLength(battery);
    size += ros::serialization::serializationLength(temp1);
    size += ros::serialization::serializationLength(temp2);
    size += ros::serialization::serializationLength(temp3);
    return size;
  }

  typedef boost::shared_ptr< ::ssl_msgs::LocalRobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_msgs::LocalRobotState_<ContainerAllocator>  const> ConstPtr;
}; // struct LocalRobotState
typedef  ::ssl_msgs::LocalRobotState_<std::allocator<void> > LocalRobotState;

typedef boost::shared_ptr< ::ssl_msgs::LocalRobotState> LocalRobotStatePtr;
typedef boost::shared_ptr< ::ssl_msgs::LocalRobotState const> LocalRobotStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ssl_msgs::LocalRobotState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ssl_msgs::LocalRobotState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ssl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::ssl_msgs::LocalRobotState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "91ec796323133e006b0a572e6a364407";
  }

  static const char* value(const  ::ssl_msgs::LocalRobotState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x91ec796323133e00ULL;
  static const uint64_t static_value2 = 0x6b0a572e6a364407ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_msgs::LocalRobotState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ssl_msgs/LocalRobotState";
  }

  static const char* value(const  ::ssl_msgs::LocalRobotState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ssl_msgs::LocalRobotState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ball_possesion 	#true if it possess, false otherwise\n\
uint8 battery		#battery level of the robot changes between [0-100]\n\
float32 temp1 		#dummy\n\
float32 temp2 		#dummy\n\
float32 temp3 		#dummy\n\
\n\
";
  }

  static const char* value(const  ::ssl_msgs::LocalRobotState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ssl_msgs::LocalRobotState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ssl_msgs::LocalRobotState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ball_possesion);
    stream.next(m.battery);
    stream.next(m.temp1);
    stream.next(m.temp2);
    stream.next(m.temp3);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalRobotState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_msgs::LocalRobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ssl_msgs::LocalRobotState_<ContainerAllocator> & v) 
  {
    s << indent << "ball_possesion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ball_possesion);
    s << indent << "battery: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery);
    s << indent << "temp1: ";
    Printer<float>::stream(s, indent + "  ", v.temp1);
    s << indent << "temp2: ";
    Printer<float>::stream(s, indent + "  ", v.temp2);
    s << indent << "temp3: ";
    Printer<float>::stream(s, indent + "  ", v.temp3);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SSL_MSGS_MESSAGE_LOCALROBOTSTATE_H

